[project]
name = "dhl-rerouter-poc"
version = "0.1.0"
requires-python = ">=3.13,<4.0"
dependencies = [
  "setuptools>=67.0.0",
  "selenium",
  "pyyaml",
  "msal",
  "requests",
  "python-dotenv>=1.0.0",
  "beautifulsoup4>=4.12.0",
  "undetected-chromedriver",
  "tzdata",
]
